gatsby-browser.js
package-lock.json
package.json

Adds a small hook that refreshes the landing page when an update was published.
Right now, the Service Worker sometimes happily serves an outdated version to the user.

reload site when update is ready

---

static/_redirects

Adds a redirect from [netlify.ledgy.com](https://netlify.ledgy.com) to www.ledgy.com so that Google doesn’t see duplicate content on different locations. (Can harm SEO apparently)

add redirect for netlify

---

gatsby-browser.js
src/components/FAQ.jsx
src/layouts/index.jsx
src/layouts/utils.jsx
src/pages/index.jsx
static/_redirects

Uses Netlify’s [language-based redirects](https://www.netlify.com/docs/redirects/#geoip-and-language-based-redirects) to send users to `/de` or `/fr`

redirect to localized version immediately

---

gatsby-config.js

Enable our custom headers on **all** pages. Previously, they were only attached to pages that are explicitly linked on our website, but missed some internal Gatsby files.
More documentation: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify

enable headers on all pages

---

src/components/Accordion.jsx
src/components/Content.jsx
src/layouts/index.jsx
src/locale/de/messages.po
src/locale/en/messages.po
src/locale/fr/messages.po
src/pages/glossary.jsx
src/pages/help.jsx

Adds a glossary page that pulls glossary terms from Contentful

Feature/lg 290/glossary page

---

src/components/CTABanner.jsx
src/pages/employee-participation-plan-templates.jsx

**Description**
- Show a different CTA banner on the PSOP page 
- Update ProductHunt link on landing page

Use custom CTABanner for PSOP landing page

---

src/components/Markdown.jsx
src/components/PublicityBanner.jsx

Rendering different output on the server depending on the time (via `isVisibleNow`) seems to mess up React. This approach always renders the `null` on the server and only creates the banner on the client (via `useEffect`)

Lg 895/render banner only on client

---

src/layouts/page.jsx

- It seems as though the `id` of a page can change over time (possibly related to routing, moving, etc.) At some point, the id we hardcoded for the calculator page ceased to match the page's actual id.
- I have instead changed the logic to check if the slug matches, which should be a more permanent (or at least more debuggable) way to identify the calculator page.

Check page slug instead of id for caculator page

---

src/components/TeamMembers.jsx
src/helpers/utilities.js
src/pages/about-us.jsx
src/styles/_components.scss

- We recently implemented an array shuffling fn to randomize team member order in every render of the about us page
- In production, hard-refreshing would cause 2 bugs: some images would randomly enlarge, and the social icons would randomly move to other people 🤷🏻‍♂️
- The fix for the images was to avoid using a css `calc` fn to calculate the size of the container
- The fix for the icon shuffling was to keep the data in a component's state, and shuffle it in a `useEffect`

LG-2766/fixAboutUsImages

---

flow-typed/index.js
src/components/forms/DemoForm.jsx
src/components/forms/Fields.jsx
src/components/forms/SubscriptionForm.jsx
src/components/forms/lib/handleDemoSubmit.js
src/helpers/constants.js

In the demo form (ledgy.com/demo/ledgy), if the response from hubspot is not a `200` we display an error message telling the user that something went wrong, and to try again. The issue is that the submit button is disabled, and the user doesn't know that to enable it he/she has to change something in the form to reset its state to `IDLE`
So, this PR
- Allows resubmitting the `DemoForm` after 1 second if a `fetch` error is encountered (without the need to update anything in the form to reset its state)

LG-2812/improveGetDemoUX

---

src/components/forms/DemoForm.jsx
src/components/forms/lib/handleDemoSubmit.js

*invalid, not unvalid.
Instead of throwing an error when an invalid email address is given in the Demo form, we send a meaningful message to the user:

Unthrow error when unvalid email in demo request

---

gatsby-config.js
package-lock.json
package.json

Change default config of `gatsby-plugin-offline` to load `page-data` from `StaleWhileRevalidate` to a `NetworkFirst` strategy:
https://github.com/gatsbyjs/gatsby/blob/2b8fe1223c49b7cb2bc28d04a79c60bf7c9221a1/packages/gatsby-plugin-offline/src/gatsby-node.js#L134

use NetworkFirst for app-data and page-data

---

src/components/forms/lib/handleDemoSubmit.js

Demo form submit:
- more of a refactor
- change is to either call `onError` or `onSuccess` when submitting to hubspot, but not both
Test steps:
- on preview test demo request still works: for company & investor

LG-3078: improve demo request

---

src/components/markdown/LongText.tsx

On calculator page, add a small margin between the content and the footer:

Lg 3513/add margin

---

gatsby-node.js
src/@types/contentful.d.ts
src/components/ChecklistWithScreenshot.tsx
src/components/ContentWithChecklist.tsx
src/components/utils/SectionHeader.tsx
src/layouts/featurePage.tsx
src/pages/index.tsx

https://ledgy.atlassian.net/browse/LG-3596?atlOrigin=eyJpIjoiNjU2MGFlYTc1MWRlNGQxNmIzYjBhZWM5NjNlMzg0Y2UiLCJwIjoiaiJ9
- possible for four checklist (top)
- button optional (top)
- allow longer text (bottom)
- can flip the side (bottom)
- checklist optional (bottom)
Post-test Todo

make link and checklist length flexible

---

src/components/forms/lib/hubspot.ts

Track `unverified_pipeline_value` for further verification from the marketing team.

Lg 3667/track unverified pipeline value

---

gatsby-node.js
src/@types/contentful.d.ts
src/components/customerStories/CustomerStoryLink.tsx
src/layouts/customerStory.tsx
src/layouts/demo.tsx
src/layouts/featurePage.tsx
src/pages/index.tsx

- new `title` field (optional) for pages for SEO: front page, feature page, demo page and customer page
- rename previous `title` as `header` for users to read

LG-3766 Create Title field for SEO 

---

gatsby-node.js
src/components/HelmetIndexLayout.tsx
src/components/lib/urlHelpers.ts

* Remove broken duplicate pages like https://ledgy.com/en/calculator/ (should be https://ledgy.com/calculator/) that harm our SEO
* Add `rel="canonical"` to all pages ([background](https://www.portent.com/blog/seo/implement-hreflang-canonical-tags-correctly.htm))
* Add missing trailing slash to internal URLs (eg. `/finance-legal-accounting` → `/finance-legal-accounting/`)

remove pages with /en/ prefix

---

src/components/forms/lib/hubspot.ts

* Send Google Analytics client ID to Hubspot when requesting a demo

get Google Analytics client ID

---

gatsby-node.js
src/@types/contentful.d.ts
src/layouts/page.tsx

- https://ledgy.atlassian.net/browse/LG-3935?atlOrigin=eyJpIjoiNGZiNjE2ZTFhMGZlNDBiZWFlNzAxZDdlNzhhZTAzNjYiLCJwIjoiaiJ9
- Added an optional `Entries` field to `Page` Contentful model, where all standard components (such as CTA, Screenshot with checklists) can be added to allow more flexibility in pages, an example can be seen here:  [Test Example](https://app.contentful.com/spaces/ojxc8xtj0owo/entries/3LqRrTTmVx2UiwliMpsf7y)
- How the test example looks on landing page:

Lg 3935/show entries on page component

---

src/styles/_components.scss
src/styles/_markdown.scss

- make markdown text smaller, = $ledgy-font-size(17px)
- click deploy/netlify details in the following checks section on this page to see the preview
- check blogs, updates, customer stories and see whether the text size makes sense

Reduce markdown text size to match other font sizes

---

gatsby-node.js
src/@types/contentful.d.ts
src/components/ContactUs/Emails.tsx
src/components/CustomButton.tsx
src/components/JobBoard.tsx
src/components/TitleWithGraphic.tsx
src/components/index.ts
src/components/lib/textHelpers.ts
src/components/nav/MobileNavbar.tsx
src/layouts/index.tsx
src/layouts/marketplace.tsx
src/redirects.js

Tickets:
- https://ledgy.atlassian.net/browse/LG-5043
- https://ledgy.atlassian.net/browse/LG-5043
1. added buttons for individual marketplace page (e.g. `.../integrations/bamboohr/`)
2. Changed a few URL snugs
- `about-us` now points to ledgy's story
- `team` now points to ledgitas page
- `jobs` replaced by `careers`, previous `.../jobs/` will be redirect to `.../careers/`, and all job ads `.../jobs/XXXXXX` will be redirected to `.../careers/XXXXXXX`

LG-5043/add custom Buttons to individual marketplace page

---

src/components/ClickCease.tsx
src/components/HelmetIndexLayout.tsx
src/components/TopBanner.tsx
src/components/nav/Nav.tsx
src/components/utils/CustomFade.tsx
src/components/utils/Icon.tsx
src/styles/_fonts.scss

Display text before loading fonts: `font-display:swap`
disable transitions on mobile: `isMobile`
Give default size to logo image :`width 80`
Lazy-load scripts waiting for usage :`defer`
Just download the website and check if it still works
Performance issues can be checked at this link https://pagespeed.web.dev/report?url=https%3A%2F%2Fledgy.com%2F

lg-5283 | Page speed improvements

---

gatsby-node.js
src/@types/contentful.d.ts
src/components/ComponentPicker.tsx
src/components/Testimonial.tsx
src/components/Testimonials.tsx
src/components/forms/DemoForm.tsx
src/components/forms/lib/handleDemoSubmit.ts
src/layouts/customLandingPage.tsx
src/layouts/demo.tsx
src/pages/index.tsx

@almasen I have splitted the PR into 3 commits to make it easier to review:
Now testimonial like the ones in the example, can be queried from contentful instead of having to hardcoding them
Now we pass the `slug` of the page from where user book the demo requests to Analytics
With this PR, we can generate 100% flexible landing pages. The behavior should be similar to the `ledgy.com/src/layouts/featurePage.tsx` file.
We query the structure of the landing pages we want to create on the `gatsby-node.js` file.
We generate the pages with the `createLocalizedPages` function on that same file. We pass the queried data to `customLandingPage.tsx` and generate the pages with that template.
An example of a generated landing page can be found at `/20vc` on the Netifly deploy

Generate custom landingpages

---

src/components/Footer.tsx

The new Z-index of the language selector is higher than the one from the social networks links. If you look closely you can see the social logos appearing over the word `Deutsh` in the first image.

Fix language selector index

---

src/components/ContactUs/Emails.tsx

As requested by Nico, I have added the legal team email on the `Contact` page

Added Legal team email to the Contact Page

---

src/components/HelmetIndexLayout.tsx
src/components/nav/NavbarButtons.tsx

Remove `defer` from `Google optimize tag` and activate only on prod
Quick fix asked by Ben: Redirect users to `app.ledgy.com` if they click on the Sign Up button

Remove defer from optimize tag 

---

src/components/ContactUs/Emails.tsx

Check that `legal@ledgy.com` is not showing anymore on [the contact page](https://deploy-preview-592--ledgy.netlify.app/contact/)

Remove `legal@ledgy.com` email address from website

---

src/components/forms/lib/handleDemoSubmit.ts
src/components/topBanners/DemoTopBanner.tsx

- Updated the `Schedule a demo` CTA to better reflect cases on smaller companies looking for a demo
- Added to events`TagManagerBigCompany` and `TagManagerSmallCompany` to better track conversions on Google Ads
- Removed the Identify call as it was only causing noise

Update CTAs and start using Adwords

---

src/components/forms/SubscriptionForm.tsx
src/components/forms/lib/handleDemoSubmit.ts
src/helpers/utilities.ts

Add an `identify` segment call when emails are submitted. 
If the user already has an ID, use the `alias` method

Add an identify segment call when emails are submitted

---

src/components/blog/PostFilters.tsx
src/pages/index.tsx

Now also the top banner can change based on location.
`(works only on preview mode)`
To test locally, visit `de/test-landingpage` & `uk/test-landingpage`

Add top banners into the Regional Component Picker
