Ledgy/ledgy.com

gatsby-config.js, package-lock.json, package.json, src/html.jsx, src/layouts/index.jsx
This reverts commit ddd9101b6644f2dc367c4b364eb40bc0c0b2f2f3.
=> Revert "update freshchat"

src/assets/scss/layout/_navbar.scss, src/layouts/index.jsx, src/layouts/style.scss, src/locale/de/messages.po, src/locale/en/messages.po
Split "Sign in" into "Sign up" and "Log in" and styled new button
=> Sign up button

gatsby-config.js, package-lock.json, package.json, src/layouts/markdown.jsx, src/markdown/blog/pre-and-post-money-option-pools.mdx, src/markdown/help/faq.mdx, src/markdown/help/getting-started.mdx
Draft for a solution to use the fancy `gatsby-image` in MDX.
Needs a proper way to define some image size and align that also works for mobile.
=> use gatsby images in MDX

src/components/Markdown.jsx, src/layouts/markdown.jsx, src/layouts/style.scss, src/layouts/team.jsx, src/locale/de/messages.po, src/locale/en/messages.po, src/markdown/blog/blockchain-notary.mdx, src/markdown/blog/convertible-loans.mdx, src/markdown/blog/csv-export.mdx, src/markdown/blog/numbered-shares.mdx, src/markdown/blog/pre-and-post-money-option-pools.mdx, src/markdown/blog/verifying-documents-on-the-blockchain.mdx, src/pages/about-us.jsx
=> add about author section to blog posts

package-lock.json, package.json
* Shoud fix math on https://www.ledgy.com/blog/pre-and-post-money-option-pools/
=> downgrade gatsby-mdx

src/layouts/index.jsx, src/layouts/style.scss, src/locale/de/messages.po, src/locale/en/messages.po, src/pages/index.jsx, src/pages/pricing.jsx
Another approach to fix the word wrap in the header.
=> fix word break in header

.editorconfig, .gitignore
@morloy adding here `.envrc` ignored file and `.editorconfig` file (same settings as on ledgy-app).
I run into not having add new lines at end of files :-).
=> Add config files

gatsby-browser.js, src/layouts/index.jsx, src/locale/de/messages.po, src/locale/en/messages.po, src/locale/fr/messages.po, src/pages/index.jsx
@morloy done as you suggested. Translations are in place.
For some strange reason, if no experiment is set in `window.experiment` (ga not available), we default to master version (first entry in array).
Feel free to change/merge the branch.
=> Add title/subtitle AB Test experiments on landing page

src/locale/de/messages.po, src/locale/en/messages.po, src/locale/fr/messages.po
=> Update some German translations

src/layouts/index.jsx
Add Youtube icon to landing page footer
=> Add Youtube icon to landing page footer

src/components/Markdown.jsx, src/layouts/style.scss
Makes our blog a bit more narrow and increases font size.
=> update blog style

src/layouts/index.jsx, src/layouts/style.scss, src/layouts/utils.jsx, src/locale/de/messages.po, src/locale/en/messages.po, src/locale/fr/messages.po, src/pages/help-center.jsx, src/pages/help.jsx, src/pages/index.jsx
Note for reviewers: please check out the links under the 'help' section in the footer and see if you have a better way of arranging them (since help center is more of a parent page and the rest can be accessed through it)
=> help center

gatsby-config.js
We solved previously making requests from ledgy.com -> www.ledgy.com.
Allow plain ledgy.com CORS, when requests come from www.ledgy.com -> ledgy.com.
=> Attempt to fix CORS www issue

src/components/Modal.jsx, src/layouts/index.jsx, src/locale/de/messages.po, src/locale/en/messages.po, src/locale/fr/messages.po
=> Add newsletter modal

src/components/PublicityBanner.jsx
Attempt to fix the banner issue.
=> always render a component in banner

src/components/SecurityRow.jsx, src/locale/de/messages.po, src/locale/en/messages.po, src/locale/fr/messages.po, src/pages/privacy.jsx, src/pages/security.jsx
Todo
*We reserve the right to update and change this Privacy Policy from time to time to reflect any changes to how we process your Personal Data or changing legal requirements. The effective date of our Privacy Policy is posted below, and we encourage you to visit our Website periodically to stay informed about our privacy practices. We will inform you about major changes.*
=> Update privacy and security page to reflect swiss hosting

src/components/HomePageHeader.jsx, src/pages/index.jsx
**Description**
- Moves `HomePageHeader` to its own component file
- Query Contentful for new home page header content
- Cycle through Contentful entries to run experiments
=> Feature/lg 520/landing page header contentful

src/components/Header.jsx, src/components/ProductHuntButton.jsx, src/pages/employee-participation-plan-templates.jsx
=> Make postId dynamic for ProductHunt button

src/components/templates/SignaturesComingSoon.jsx
=> improve style coming soon list

src/components/Markdown.jsx, src/layouts/contentfulPage.jsx, src/layouts/style.scss
Add a `<Lead>` component to Contentful Markdown:
=> add Lead component

flow-typed/index.js, src/components/Accordion.jsx, src/pages/404.jsx, src/pages/contact.jsx
- Update 404 page to be a bit friendlier and SEO-able
- Add contact page description
=> Feature/lg 1014/update seo

gatsby-config.js, src/helpers/constants.js, src/helpers/contentSecurityPolicy.js, src/helpers/index.js, src/layouts/index.jsx
* Replace Freshchat with Hubspot Chat
* Add a CSP helper to separate policies into modules
* Add some missing CSP entries for tracking
=> Integrate HubSpot Chat

src/layouts/style.scss
=> update blockquote style

flow-typed/index.js, package.json, src/components/customerStories/CompanySummary.jsx, src/layouts/customerStory.jsx
- make optional `funding` company field
=> Company summary: some optional  fields

src/components/RequestDemoForm.jsx, src/components/lib/demoAccess.js
- Only email and employee count are now required
=> Make person and company name optional in demo access form

build.sh, getTranslations.sh, src/assets/js/segment.js, src/components/DynamicTrans.jsx, src/components/Header.jsx, src/components/customerStories/CompanySummary.jsx, src/helpers/dynamicTranslations.js
Adds framework to translate pages from Contentful with Loco & lingui.
As an example, all page titles from Contentful are translated, see eg. https://deploy-preview-305--ledgy.netlify.com/de/legal/privacy-policy/
=> Lg 1206/translate contentful

src/components/templates/DigitalSignatures.jsx, src/components/templates/index.js, src/helpers/pageTextHelpers.jsx, src/pages/employee-participation-plan-templates.jsx
=> Feature/lg 1365/remove coming soon

package-lock.json, package.json, src/pages/company-pricing.jsx
=> Update @ledgy/pricing package

src/pages/investor-pricing.jsx
**Description**
- Change email from contact to sales on investor pricing page
=> LG-1472: Sales contact for investor pricing

package-lock.json, package.json, src/pages/company-pricing.jsx
=> Use latest ledgy-pricing version

src/pages/contact.jsx
=> add sales email to contact page

src/pages/index.jsx
Attempt to fix our currently suboptimal title on Google 🤣
=> attempt to fix the title

flow-typed/index.js, gatsby-node.js, src/components/Footer.jsx, src/components/MainHeaderLayout.jsx, src/components/RequestDemoModal.jsx, src/components/SubscriptionModal.jsx, src/components/forms/Fields.jsx, src/components/forms/RequestDemoForm.jsx, src/components/forms/SignupForm.jsx, src/components/forms/SubscriptionForm.jsx, src/components/forms/index.js, src/components/forms/lib/demoAccess.js, src/components/forms/lib/handleSignupForm.js, src/components/forms/lib/handleSignupFormSubmit.js, src/components/forms/lib/index.js, src/components/forms/lib/subscription.js, src/components/lib/index.js, src/components/templates/TemplateFAQs.jsx, src/helpers/constants.js, src/layouts/index.jsx, src/layouts/signup.jsx, src/pages/signup.jsx, src/styles/_components.scss, src/styles/_deco-shapes.scss, src/styles/_utilities.scss
The only `signup` content available so far has been named `main` in Contentful. So, to see the page rendered go to `.../signup/main`
=> Lg 2420/signup marketing page

package-lock.json, package.json
Seems like the current version of Gatsby breaks the preview again…
=> downgrade gatsby to fix preview, again

src/components/forms/lib/constants.js, src/components/forms/lib/handleDemoSubmit.js, src/layouts/demo.jsx
Implement the updated pipeline value for companies
=> Lg 2699/fix pipeline value

src/components/ExternalLogoRow.jsx, src/components/Feature.jsx, src/components/G2AndCapterraStrip.jsx, src/components/ImageModal.jsx, src/components/Modal.jsx, src/components/SubscriptionModal.jsx, src/layouts/featurePage.jsx, src/pages/index.jsx, src/styles/_components.scss, src/styles/_index.scss, src/styles/_modal.scss, src/styles/_variables.scss
- Creates the new `ImageModal` component, which allows us to enlarge images on click. For now, applied to `<Feature />`
- Adjusts font size in logo banners
- Decreases image quality in front page image, as it currently is too much, affecting loading times
=> Lg 2983/quick wins

package-lock.json, package.json, src/pages/company-pricing.jsx
- use new Pricing library
- to be released after app deploy
=> Update pricing library version

src/components/forms/lib/constants.js
🎉 💯 ⚡ 
- Calendar links use Armon's calendar
=> Update demo to company and investor meeting links

src/@types/contentful.d.ts, src/components/ContentWithChecklist.tsx, src/components/LogoBanner.tsx, src/components/TitleWithGraphic.tsx, src/components/index.ts, src/pages/hiddenBoost.tsx, src/styles/_components.scss
=> create logo banner

src/pages/contact.tsx
=> fix contact page

package-lock.json, package.json, src/pages/company-pricing.tsx
- pricing package update
- found a reference to old plan (Premium => Growth)
=> Update pricing version

src/components/ChecklistWithScreenshot.tsx, src/components/ContentWithChecklist.tsx, src/components/TitleWithGraphic.tsx
=> Lg 3456/flexibilize components

src/components/forms/lib/handleDemoSubmit.ts
specs https://ledgy.atlassian.net/browse/LG-3576?atlOrigin=eyJpIjoiN2NiZTkyMWU2Y2VkNGZlMjljZDQwNGUxMTYwMmE4MzQiLCJwIjoiaiJ9
=> add Email address to url

package.json
includes employee scenarios now
=> upgrade pricing

src/components/lib/urlHelpers.ts, src/components/markdown/Markdown.tsx
=> fix mailto links

package-lock.json, src/layouts/team.tsx
=> Update team page

gatsby-node.js, src/@types/contentful.d.ts, src/components/LogoBanner.tsx, src/pages/index.tsx
- https://ledgy.atlassian.net/browse/LG-4027?atlOrigin=eyJpIjoiNmEzYWUyOGYzMWFjNGI1ZjhjYzNhNjBiMzFlMmRjMDYiLCJwIjoiaiJ9
- on demo page
- on front page
- on phones
=> Lg 4027/add text to logo banner

src/components/nav/MobileNavbar.tsx, src/components/nav/NavbarButtons.tsx, src/helpers/marketing.ts
* Show a **Sign Up** button for first time visitors that don’t have an account on Ledgy yet
=> add SignupLoginButton

src/components/forms/lib/handleDemoSubmit.ts
* Add a special tag to the demo page (https://ledgy.com/demo/ledgy/#book) that always redirect to the sales calendar
=> add always book hook

gatsby-node.js, src/@types/contentful.d.ts, src/components/CallToAction.tsx, src/components/CardLink.tsx, src/components/ComponentPicker.tsx, src/components/RequestDemoButton.tsx, src/components/TitleWithGraphic.tsx, src/components/TopBanner.tsx, src/components/lib/urlHelpers.ts, src/components/markdown/Markdown.tsx, src/components/nav/NavbarButtons.tsx, src/components/utils/Button.tsx, src/helpers/constants.ts, src/layouts/featurePage.tsx, src/layouts/page.tsx, src/pages/index.tsx
* Add optional buttons to the `TitleWithGraphic` component
On **Feature Page 2021**
On **Title with Graphic** block
=> Lg 4222/add buttons to titles

build.sh, gatsby-config.js, netlify.toml, package-lock.json, package.json, static/_redirects
* Replace the deprecated `gatsby-plugin-netlify-cache` with the new `@netlify/plugin-gatsby`
=> enable incremental builds and netlify cache

src/components/markdown/Markdown.tsx, src/components/teamMembers/getTeamDescriptions.tsx
Sample page: http://localhost:8000/jobs/biz-dev-associate
=> render GIF in Markdown

src/components/BlogsList.tsx, src/components/CardLink.tsx, src/components/UpdatesList.tsx, src/components/utils/ButtonGroup.tsx, src/components/utils/index.ts, src/helpers/constants.ts, src/styles/_buttons.scss, src/styles/_components.scss
- Specs: https://ledgy.atlassian.net/browse/LG-4408
- large view
- medium view
- small view
=> Lg 4408/add category buttons to blogs and updates page

src/components/JobBoard.tsx, src/components/teamMembers/getTeamDescriptions.tsx
Limit the job board to posts that are in the `Zurich` location.
=> limit job board location

src/components/Ledgistats.tsx, src/components/lib/textHelpers.ts
- adds `marketplace` link in footer
- bumps up header size in ledgistats
=> Lg 5140/small improvements

src/@types/contentful.d.ts, src/components/PublicityBanner.tsx, src/components/SubscriptionModal.tsx, src/components/forms/SubscriptionForm.tsx, src/components/forms/lib/subscription.ts, src/components/index.ts, src/components/popup/NewsletterPopUp.tsx, src/components/popup/PopUpCard.tsx, src/components/popup/index.ts, src/layouts/index.tsx, src/styles/_buttons.scss, src/styles/_components.scss, src/styles/_utilities.scss
Test that the form appears after 10 seconds on the various `blogs/*` pages. 
Try to submit your email and check if it shows a thank you message.
Bonus: If you know an effective way to clear out the interval please teach me :)  (I know `clearTimeout()` but I am having some problems saving the `timeoutId`, I also tried with the state)
=> lg-5282 | Newsletter form

gatsby-node.js
=> ledgy.com/about-us/ should now work in all languages

src/@types/contentful.d.ts, src/components/CookieBanner.tsx, src/components/PublicityBanner.tsx, src/components/nav/Nav.tsx, src/components/nav/TopUpdateBanner.tsx, src/components/popup/NewsletterPopUp.tsx, src/redirects.js, src/styles/_components.scss
We should now be able to add a banner at the top of the page. The content is managed from contentful. We will use it for the state of equity report
=> Top banner for updates

src/components/CallToAction.tsx, src/components/DemoTopBanner.tsx
=> Fix intrapage url scroll

src/components/forms/lib/handleDemoSubmit.ts, src/helpers/utilities.ts
I added some `identify` calls for Amplitude. They will help us understand user behavior and analyze what users that convert do on our landing page.
Not really testable. If you want I can grant you access and you can see the data appearing on Amplitude ;)
=> Identify user that book demo

src/@types/contentful.d.ts, src/components/TopBanner.tsx, src/components/index.ts, src/components/topBanners/DemoTopBanner.tsx, src/components/topBanners/ExtraLinkTopBanner.tsx, src/components/topBanners/index.ts, src/pages/index.tsx
=> Added the get started for free CTA on the main landing page

src/components/CookieBanner.tsx, src/styles/_components.scss
Display the Coockie banner on the right side of the page on large screens.
=> Update Coockie banner appearance

.gitignore, src/components/CookieBanner.tsx, src/components/PublicityBanner.tsx, src/components/lib/index.ts, src/components/lib/isSmallScreen.ts, src/components/popup/PopUpCard.tsx, src/styles/_components.scss
Quick update on the banner UI
**Ticket:** https://ledgy.atlassian.net/jira/software/projects/LG/boards/2?issueParent=15593&selectedIssue=LG-5644
**Extra:** Solve a bug that was preventing clicks before accepting the coockies
=> Update the `CookieBanner` on mobile

src/components/TopBanner.tsx
In order to change the `button color` of the thanks you page, I have slightly changed the `isPrimary` check!
=> Increase the number of primary buttons

src/helpers/snippets.ts
Switching to new Segment account
=> switch segment account

gatsby-node.js, src/@types/contentful.d.ts, src/components/ComponentPicker.tsx, src/components/LargeTestimonial.tsx, src/components/markdown/LongText.tsx, src/pages/index.tsx
Added a new type of `Contentful` section for large testimonials
What to test:
Make sure that the landing page with this new section loads
=> Add large testimonial

src/components/forms/lib/constants.ts, src/components/forms/lib/getUrlFromCountryCode.ts, src/components/forms/lib/handleDemoSubmit.ts
Redirect users to different Hubspot calendars based on IP location :)
=> New feature/redirect on location

src/components/forms/SubscriptionForm.tsx, src/components/forms/lib/constants.ts, src/components/forms/lib/formTypes.ts, src/components/forms/lib/handleDemoSubmit.ts, src/components/forms/lib/hubspot.ts, src/components/forms/lib/index.ts
Update the newsletter subscription flow from storing users in Mixpanel to storing users on Hubspot
=> Add newsletter subscribers directly in Hubspot

build.sh, package-lock.json, package.json
Rename “Starting 300 / month” to “Contact sales”
=> contact sales

src/components/forms/DemoForm.tsx, src/components/forms/lib/getPartners.ts, src/components/forms/lib/index.ts, src/components/nav/Nav.tsx, src/layouts/index.tsx
=> Take the partnership list from Contentful

src/components/nav/DropdownItem.tsx
Add tracker for the menu link
This way we will be able to understand which are the most used links on the landing page
Test:
=> Add tracker for menu link

gatsby-node.js, src/@types/contentful.d.ts, src/components/ComponentPicker.tsx, src/components/competitorsTable/CompetitorsTable.tsx, src/components/competitorsTable/TableRow.tsx, src/components/competitorsTable/TableSection.tsx, src/components/competitorsTable/index.ts, src/components/utils/CustomFade.tsx, src/helpers/utilities.ts, src/layouts/customLandingPage.tsx, src/pages/index.tsx, src/styles/_components.scss
Recently, many prospects in the UK compared us to our competitors.
For this reason, we are adding a new component.
The competitor table
An example of this component can be found at `/lp-capdesk-uk`
=> Competitor comparison table

gatsby-browser.js
Remove reload when the user enters the website
=> disable page reload

src/styles/_navbar.scss
Support request: https://ledgy.slack.com/archives/C02J160DV6K/p1652951501089749
=> Add bottom margin on mobile `Navbar`

src/components/pricing/CompanyPricingCTAs.tsx
Change climate discount application from email to sales@ledgy.com to a typeform which notifies the climate action committee.
=> Change climate discount application

src/components/forms/DemoForm.tsx, src/components/forms/Fields.tsx, src/components/forms/lib/constants.ts, src/components/forms/lib/handleDemoSubmit.ts, src/components/topBanners/DemoTopBanner.tsx, src/layouts/demo.tsx
Update the demo lead form logic based on feedback from Armon and Charlie
=> Update Demo lead form logic

.github/pull_request_template.md, src/@types/contentful.d.ts, src/components/CalculatorHeader.tsx, src/components/ProductHuntButton.tsx, src/components/TopBanner/DemoTopBanner.tsx, src/components/TopBanner/ExtraLinkTopBanner.tsx, src/components/TopBanner/ProductHuntTopBanner.tsx, src/components/TopBanner/TopBanner.tsx, src/components/TopBanner/TopBannerLayout.tsx, src/components/TopBanner/index.ts, src/components/TopBanner/lib/constants.ts, src/components/TopBanner/lib/index.ts, src/components/index.ts, src/components/productHuntButtons/PHEmployeeCompensationButton.tsx, src/components/productHuntButtons/PHFundraisingCalculatorButton.tsx, src/components/productHuntButtons/index.ts, src/components/topBanners/index.ts, src/layouts/demo.tsx, src/styles/_components.scss
Create a new `TopBanner` type that has a `Product Hunt` secondary button.
[Ticket](https://ledgy.atlassian.net/browse/LG-6437?atlOrigin=eyJpIjoiMjMxYjkzM2Y2NjdmNDRkY2E4YzE3YTQ5YmVhOTM5YmQiLCJwIjoiaiJ9)
See a preview of the component at: https://deploy-preview-692--ledgy.netlify.app/test-landingpage/
=> Add a new `TopBanner` type (`product-hunt`)

src/components/productHuntButtons/PHEmployeeCompensationButton.tsx
=> update productHunt url

package-lock.json, package.json, src/components/Explore/ExploreSection.tsx, src/components/TestimonialsCarousel/LogosBar.tsx, src/components/TestimonialsCarousel/TestimonialsCarousel.tsx, src/styles/_logos.scss, src/styles/_twocolumnslayout.scss
=> Small UI fixes & updtate Pricing

gatsby-config.js, gatsby-node.js, src/@types/contentful.d.ts, src/components/ComponentPicker.tsx, src/components/HelmetIndexLayout.tsx, src/components/PartnershipLogos/PartnershipLogos.tsx, src/components/PartnershipLogos/index.ts, src/components/PartnershipLogos/lib/getPartnerLogos.ts, src/components/PartnershipLogos/lib/index.ts, src/components/RegionalComponentPicker.tsx, src/components/StaticBlockPicker.tsx, src/components/TopBanner/TopBanner.tsx, src/components/competitorsTable/CompetitorsTable.tsx, src/components/forms/DemoForm.tsx, src/i18n-config.js, src/layouts/customLandingPage.tsx, src/layouts/index.tsx, src/layouts/utils.tsx, src/pages/index.tsx, src/styles/_index.scss, src/styles/_partnershiplogos.scss, static/_redirects
Add a partner logo section in the company pricing page
[Preview](https://deploy-preview-700--ledgy.netlify.app/company-pricing/)
Inspired from the screenshot below.
Taken from this  [page](https://www.notion.so/startups)
+ Small padding fixes
=> Add `partnerLogos` CTA

src/components/blog/lib/getMainTag.ts
Fix small titles on the blog page
=> Fix blog tags

src/styles/_blog.scss
=> Fix background color 

src/components/lib/textHelpers.ts
=> Add implicit to contact
